# Workflow for processing and publishing bikeshed proposals to github pages
name: publish specification
on:
  # only concerned with changes in the main branch
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: install bikeshed
        run: |
          python3 -m pip install --upgrade bikeshed
          bikeshed update

      - name: generate html
        run: bikeshed spec ldesinldp.bs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .
